language: python
python:
  - "3.6"      # current default Python on Travis CI
# command to install dependencies

install:
  - pip install -r requirements.txt

# command to run tests
script:
  - pytest

# Deploy code to lambda
deploy:
  provider: lambda
  access_key_id: ${AWS_ACCESS_KEY_ID}
  secret_access_key: ${AWS_ACCESS_KEY_ID}
  function_name: POTF-Lyrics-Bot
  edge: true # opt in to dpl v2
  region: us-east-1 # censor later
  role: arn:aws:iam::599595163955:role/FEHGauntletBot # censor later
  handler_name: lambda_handler
  runtime: python3.6
  on:
      branch: AWS
  # module_name	Name of the module that exports the handler — type: string, requires: handler_name, default: index
  # description	Description of the Lambda being created or updated — type: string
  # timeout	Function execution time (in seconds) at which Lambda should terminate the function — type: string, default: 3
  # memory_size	Amount of memory in MB to allocate to this Lambda — type: string, default: 128
  # subnet_ids	List of subnet IDs to be added to the function — type: string or array of strings, note: Needs the ec2:DescribeSubnets and ec2:DescribeVpcs permission for the user of the access/secret key to work
  # security_group_ids	List of security group IDs to be added to the function — type: string or array of strings, note: Needs the ec2:DescribeSecurityGroups and ec2:DescribeVpcs permission for the user of the access/secret key to work
  # environment	List of Environment Variables to add to the function — type: string or array of strings, alias: environment_variables, format: /[\w\-]+=.+/, note: Can be encrypted for added security
  # dead_letter_arn	ARN to an SNS or SQS resource used for the dead letter queue. — type: string
  # kms_key_arn	KMS key ARN to use to encrypt environment_variables. — type: string
  # tracing_mode	Tracing mode — type: string, default: PassThrough, known values: Active, PassThrough, note: Needs xray:PutTraceSegments xray:PutTelemetryRecords on the role
  # layers	Function layer arns — type: string or array of strings
  # function_tags	List of tags to add to the function — type: string or array of strings, format: /[\w\-]+=.+/, note: Can be encrypted for added security
  # publish	Create a new version of the code instead of replacing the existing one. — type: boolean
  # zip	Path to a packaged Lambda, a directory to package, or a single file to package — type: string, default: .
  # dot_match	Include hidden .* files to the zipped archive — type: boolean
